service: ultrainfo
image: turbothad/ultrainfo

servers:
  web:
    - <%= ENV.fetch("ULTRAINFO_SERVER", "87.99.128.125") %>

proxy:
  ssl: true
  host: <%= ENV.fetch("ULTRAINFO_HOST", "ultrainfo.org") %>
  forward_headers: true
  healthcheck:
    path: /up
    interval: 3
    timeout: 5

registry:
  server: ghcr.io
  username: <%= ENV.fetch("KAMAL_REGISTRY_USERNAME", "turbothad") %>
  password:
    - KAMAL_REGISTRY_PASSWORD

env:
  secret:
    - RAILS_MASTER_KEY
  clear:
    RAILS_LOG_LEVEL: info
    SOLID_QUEUE_IN_PUMA: true

aliases:
  console: app exec --interactive --reuse "bin/rails console"
  shell: app exec --interactive --reuse "bash"
  logs: app logs -f
  dbc: app exec --interactive --reuse "bin/rails dbconsole"

volumes:
  - "/var/lib/ultrainfo:/rails/storage"

asset_path: /rails/public/assets

builder:
  arch: amd64
  args:
    ULTRAINFO_VERSION: <%= ENV.fetch("ULTRAINFO_VERSION", "0.0.0-dev") %>
    ULTRAINFO_REVISION: <%= ENV.fetch("ULTRAINFO_REVISION") { `git rev-parse HEAD`.strip } %>
  provenance: mode=max
  sbom: true

ssh:
  user: deploy
